### ISSUE TITLE
Ideas for the API

### ISSUE THREAD

**Issue by MortenHofft** [gbif/col-debug-tools#2]
**Small ideas for things i often miss in our API and in this one as well**
Might be misunderstanding. Might already be planned. Might already have been considered and discarded. Might be terribly bad practice. But here goes:

As a consumer, creating a small app like this one it is useful to have:

* keys by its pretty name. Say a dataset title to go with the dataset key. If the key is there it is probably because you want to link to it and you typically want to do that using an informative description. When not there you end up doing 500 calls from the client or creating a proxy for everything. Or deciding that it isn't important enough. Neither is ideal. It is redundant, i get that, but useful.
* Somewhere to get all enums. There is currently a discrepancy between the enums listed in the docs and the ones that the API actually use. Having a way to get the live ones actually used is useful to keep the app up to date.

more to come ... perhaps

**Comment by mdoering** [comment]
i was just about to suggest a enum service. will do that in no time!

**Comment by mdoering** [comment]
http://api.col.plus/vocab/rank
http://api.col.plus/vocab/

**Comment by mdoering** [comment]
If you have further ideas or find bugs please file them here: https://github.com/Sp2000/colplus-backend/issues

**Comment by MattBlissett** [comment]
Perhaps this whole repository should be moved to Sp2000?
